---
 - hosts: grp1
   become: true
   vars_prompt:
    - name: "user_name"
      prompt: "enter the user name:"

    - name: "user_password"
      prompt: "enter password"
      private: yes
      encrypt: "md5_crypt"
      confirm: yes
